const countries = {
  ad: { name: "Andorra", countryCode: "ad" },
  ae: { name: "United Arab Emirates", countryCode: "ae" },
  af: { name: "Afghanistan", countryCode: "af" },
  ag: { name: "Antigua and Barbuda", countryCode: "ag" },
  ai: { name: "Anguilla", countryCode: "ai" },
  al: { name: "Albania", countryCode: "al" },
  am: { name: "Armenia", countryCode: "am" },
  ao: { name: "Angola", countryCode: "ao" },
  aq: { name: "Antarctica", countryCode: "aq" },
  ar: { name: "Argentina", countryCode: "ar" },
  as: { name: "American Samoa", countryCode: "as" },

  at: {
    name: "Austria",
    countryCode: "at",
    customSvg: {
      viewBoxWidth: 1800,
      viewBoxHeight: 2700,
      viewBoxX: 0,
      viewBoxY: -200,
    },
  },
  au: { name: "Australia", countryCode: "au" },
  aw: { name: "Aruba", countryCode: "aw" },
  ax: { name: "Aland Islands", countryCode: "ax" },
  az: { name: "Azerbaijan", countryCode: "az" },
  ba: { name: "Bosnia and Herzegovina", countryCode: "ba" },
  bb: { name: "Barbados", countryCode: "bb" },
  bd: { name: "Bangladesh", countryCode: "bd" },
  be: { name: "Belgium", countryCode: "be" },
  bf: { name: "Burkina Faso", countryCode: "bf" },
  bg: { name: "Bulgaria", countryCode: "bg" },
  bh: { name: "Bahrain", countryCode: "bh" },
  bi: { name: "Burundi", countryCode: "bi" },
  bj: { name: "Benin", countryCode: "bj" },
  bl: { name: "Saint Barthélemy", countryCode: "bl" },
  bm: { name: "Bermuda", countryCode: "bm" },
  bn: { name: "Brunei Darussalam", countryCode: "bn" },
  bo: { name: "Bolivia", countryCode: "bo" },
  br: { name: "Brazil", countryCode: "br" },
  bs: { name: "Bahamas", countryCode: "bs" },
  bt: { name: "Bhutan", countryCode: "bt" },
  bw: { name: "Botswana", countryCode: "bw" },
  by: { name: "Belarus", countryCode: "by" },
  bz: { name: "Belize", countryCode: "bz" },
  ca: { name: "Canada", countryCode: "ca" },
  cc: { name: "Cocos (Keeling) Islands", countryCode: "cc" },
  cf: { name: "Central African Republic", countryCode: "cf" },
  cg: { name: "Republic of the Congo", countryCode: "cg" },
  ch: { name: "Switzerland", countryCode: "ch" },
  ci: { name: "Côte D'Ivoire", countryCode: "ci" },
  ck: { name: "Cook Islands", countryCode: "ck" },
  cl: { name: "Chile", countryCode: "cl" },
  cm: { name: "Cameroon", countryCode: "cm" },
  cn: { name: "China", countryCode: "cn" },
  co: { name: "Colombia", countryCode: "co" },
  cr: { name: "Costa Rica", countryCode: "cr" },
  cu: { name: "Cuba", countryCode: "cu" },
  cv: { name: "Cape Verde", countryCode: "cv" },
  cw: { name: "Curaçao", countryCode: "cw" },
  cx: { name: "Christmas Island", countryCode: "cx" },
  cy: { name: "Cyprus", countryCode: "cy" },
  cz: { name: "Czech Republic", countryCode: "cz" },
  de: { name: "Germany", countryCode: "de" },
  dj: { name: "Djibouti", countryCode: "dj" },
  dk: { name: "Denmark", countryCode: "dk" },
  dm: { name: "Dominica", countryCode: "dm" },
  do: { name: "Dominican Republic", countryCode: "do" },
  dz: { name: "Algeria", countryCode: "dz" },
  ec: { name: "Ecuador", countryCode: "ec" },
  ee: { name: "Estonia", countryCode: "ee" },
  eg: { name: "Egypt", countryCode: "eg" },
  eh: { name: "Western Sahara", countryCode: "eh" },
  er: { name: "Eritrea", countryCode: "er" },
  es: { name: "Spain", countryCode: "es" },
  et: { name: "Ethiopia", countryCode: "et" },
  fi: { name: "Finland", countryCode: "fi" },
  fj: { name: "Fiji", countryCode: "fj" },
  fk: { name: "Philippines", countryCode: "fk" },
  fo: { name: "Faroe Islands", countryCode: "fo" },
  fr: { name: "France", countryCode: "fr" },
  ga: { name: "Gabon", countryCode: "ga" },
  gb: { name: "United Kingdom", countryCode: "gb" },
  gd: { name: "Grenada", countryCode: "gd" },
  ge: { name: "Georgia", countryCode: "ge" },
  gf: { name: "French Guinea", countryCode: "gf" },
  gg: { name: "Guernsey", countryCode: "gg" },
  gh: { name: "Ghana", countryCode: "gh" },
  gi: { name: "Gibraltar", countryCode: "gi" },
  gl: { name: "Greenland", countryCode: "gl" },
  gm: { name: "Gambia", countryCode: "gm" },
  gn: { name: "Guinea", countryCode: "gn" },
  gp: { name: "Guadeloupe", countryCode: "gp" },
  gq: { name: "Equatorial Guinea", countryCode: "gq" },
  gr: { name: "Greece", countryCode: "gr" },
  gs: {
    name: "South Georgia and the South Sandwich Islands",
    countryCode: "gs",
  },

  gt: { name: "Guatemala", countryCode: "gt" },
  gu: { name: "Guam", countryCode: "gu" },
  gw: { name: "Guinea-Bissau", countryCode: "gw" },
  gy: { name: "Guyana", countryCode: "gy" },
  hk: { name: "Hong Kong", countryCode: "hk" },
  hm: { name: "Heard and Mcdonald Islands", countryCode: "hm" },
  hn: { name: "Honduras", countryCode: "hn" },
  hr: { name: "Croatia", countryCode: "hr" },
  ht: { name: "Haiti", countryCode: "ht" },
  hu: { name: "Hungary", countryCode: "hu" },
  id: { name: "Indonesia", countryCode: "id" },
  ie: { name: "Ireland", countryCode: "ie" },
  il: { name: "Israel", countryCode: "il" },
  im: { name: "Isle of Man", countryCode: "im" },
  in: { name: "India", countryCode: "in" },
  io: { name: "British Indian Ocean Territory", countryCode: "io" },
  iq: { name: "Iraq", countryCode: "iq" },
  ir: { name: "Iran", countryCode: "ir" },
  is: { name: "Iceland", countryCode: "is" },
  it: { name: "Italy", countryCode: "it" },
  jm: { name: "Jamaica", countryCode: "jm" },
  jo: { name: "Jordan", countryCode: "jo" },
  jp: { name: "Japan", countryCode: "jp" },
  ke: { name: "Kenya", countryCode: "ke" },
  kg: { name: "Kyrgyzstan", countryCode: "kg" },
  kh: { name: "Camboda", countryCode: "kh" },
  ki: { name: "Kiribati", countryCode: "ki" },
  km: { name: "Comoros", countryCode: "km" },
  kn: { name: "Saint Kitts and Nevis", countryCode: "kn" },
  kp: { name: "North Korea", countryCode: "kp" },
  kr: { name: "South Korea", countryCode: "kr" },
  kw: { name: "Kuwait", countryCode: "kw" },
  ky: { name: "Cayman Islands", countryCode: "ky" },
  kz: { name: "Kazakhstan", countryCode: "kz" },
};

export default countries;
