const countries = {
  ad: { name: "Andorra", countryCode: "ad" },
  ae: { name: "United Arab Emirates", countryCode: "ae" },
  af: { name: "Afghanistan", countryCode: "af" },
  ag: { name: "Antigua and Barbuda", countryCode: "ag" },
  ai: { name: "Anguilla", countryCode: "ai" },
  al: { name: "Albania", countryCode: "al" },
  am: { name: "Armenia", countryCode: "am" },
  ao: { name: "Angola", countryCode: "ao" },
  aq: { name: "Antarctica", countryCode: "aq" },
  ar: { name: "Argentina", countryCode: "ar" },
  as: { name: "American Samoa", countryCode: "as" },

  at: {
    name: "Austria",
    countryCode: "at",
    customSvg: {
      viewBoxWidth: 1800,
      viewBoxHeight: 2700,
      viewBoxX: 0,
      viewBoxY: -200,
    },
  },
  au: { name: "Australia", countryCode: "au" },
  aw: { name: "Aruba", countryCode: "aw" },
  ax: { name: "Aland Islands", countryCode: "ax" },
  az: { name: "Azerbaijan", countryCode: "az" },
  ba: { name: "Bosnia and Herzegovina", countryCode: "ba" },
  bb: { name: "Barbados", countryCode: "bb" },
  bd: { name: "Bangladesh", countryCode: "bd" },
  be: { name: "Belgium", countryCode: "be" },
  bf: { name: "Burkina Faso", countryCode: "bf" },
  bg: { name: "Bulgaria", countryCode: "bg" },
  bh: { name: "Bahrain", countryCode: "bh" },
  bi: { name: "Burundi", countryCode: "bi" },
  bj: { name: "Benin", countryCode: "bj" },
  bl: { name: "Saint Barthélemy", countryCode: "bl" },
  bm: { name: "Bermuda", countryCode: "bm" },
  bn: { name: "Brunei Darussalam", countryCode: "bn" },
  bo: { name: "Bolivia", countryCode: "bo" },
  br: { name: "Brazil", countryCode: "br" },
  bs: { name: "Bahamas", countryCode: "bs" },
  bt: { name: "Bhutan", countryCode: "bt" },
  bw: { name: "Botswana", countryCode: "bw" },
  by: { name: "Belarus", countryCode: "by" },
  bz: { name: "Belize", countryCode: "bz" },
  ca: { name: "Canada", countryCode: "ca" },
  cc: { name: "Cocos (Keeling) Islands", countryCode: "cc" },
  cf: { name: "Central African Republic", countryCode: "cf" },
  cg: { name: "Republic of the Congo", countryCode: "cg" },
  ch: { name: "Switzerland", countryCode: "ch" },
  ci: { name: "Côte D'Ivoire", countryCode: "ci" },
  ck: { name: "Cook Islands", countryCode: "ck" },
  cl: { name: "Chile", countryCode: "cl" },
  cm: { name: "Cameroon", countryCode: "cm" },
  cn: { name: "China", countryCode: "cn" },
  co: { name: "Colombia", countryCode: "co" },
  cr: { name: "Costa Rica", countryCode: "cr" },
  cu: { name: "Cuba", countryCode: "cu" },
  cv: { name: "Cape Verde", countryCode: "cv" },
  cw: { name: "Curaçao", countryCode: "cw" },
  cx: { name: "Christmas Island", countryCode: "cx" },
  cy: { name: "Cyprus", countryCode: "cy" },
  cz: { name: "Czech Republic", countryCode: "cz" },
  de: { name: "Germany", countryCode: "de" },
  dj: { name: "Djibouti", countryCode: "dj" },
  dk: { name: "Denmark", countryCode: "dk" },
  dm: { name: "Dominica", countryCode: "dm" },
  do: { name: "Dominican Republic", countryCode: "do" },
  dz: { name: "Algeria", countryCode: "dz" },
  ec: { name: "Ecuador", countryCode: "ec" },
  ee: { name: "Estonia", countryCode: "ee" },
  eg: { name: "Egypt", countryCode: "eg" },
  eh: { name: "Western Sahara", countryCode: "eh" },
  er: { name: "Eritrea", countryCode: "er" },
  es: { name: "Spain", countryCode: "es" },
  et: { name: "Ethiopia", countryCode: "et" },
  fi: { name: "Finland", countryCode: "fi" },
  fj: { name: "Fiji", countryCode: "fj" },
  fk: { name: "Falkland Islands (Islas Malvinas)", countryCode: "fk" },
  fo: { name: "Faroe Islands", countryCode: "fo" },
  fr: { name: "France", countryCode: "fr" },
  ga: { name: "Gabon", countryCode: "ga" },
  gb: { name: "United Kingdom", countryCode: "gb" },
  gd: { name: "Grenada", countryCode: "gd" },
  ge: { name: "Georgia", countryCode: "ge" },
  gf: { name: "French Guinea", countryCode: "gf" },
  gg: { name: "Guernsey", countryCode: "gg" },
  gh: { name: "Ghana", countryCode: "gh" },
  gi: { name: "Gibraltar", countryCode: "gi" },
  gl: { name: "Greenland", countryCode: "gl" },
  gm: { name: "Gambia", countryCode: "gm" },
  gn: { name: "Guinea", countryCode: "gn" },
  gp: { name: "Guadeloupe", countryCode: "gp" },
  gq: { name: "Equatorial Guinea", countryCode: "gq" },
  gr: { name: "Greece", countryCode: "gr" },
  gs: {
    name: "South Georgia and the South Sandwich Islands",
    countryCode: "gs",
  },

  gt: { name: "Guatemala", countryCode: "gt" },
  gu: { name: "Guam", countryCode: "gu" },
  gw: { name: "Guinea-Bissau", countryCode: "gw" },
  gy: { name: "Guyana", countryCode: "gy" },
  hk: { name: "Hong Kong", countryCode: "hk" },
  hm: { name: "Heard and Mcdonald Islands", countryCode: "hm" },
  hn: { name: "Honduras", countryCode: "hn" },
  hr: { name: "Croatia", countryCode: "hr" },
  ht: { name: "Haiti", countryCode: "ht" },
  hu: { name: "Hungary", countryCode: "hu" },
  id: { name: "Indonesia", countryCode: "id" },
  ie: { name: "Ireland", countryCode: "ie" },
  il: { name: "Israel", countryCode: "il" },
  im: { name: "Isle of Man", countryCode: "im" },
  in: { name: "India", countryCode: "in" },
  io: { name: "British Indian Ocean Territory", countryCode: "io" },
  iq: { name: "Iraq", countryCode: "iq" },
  ir: { name: "Iran", countryCode: "ir" },
  is: { name: "Iceland", countryCode: "is" },
  it: { name: "Italy", countryCode: "it" },
  jm: { name: "Jamaica", countryCode: "jm" },
  jo: { name: "Jordan", countryCode: "jo" },
  jp: { name: "Japan", countryCode: "jp" },
  ke: { name: "Kenya", countryCode: "ke" },
  kg: { name: "Kyrgyzstan", countryCode: "kg" },
  kh: { name: "Cambodia", countryCode: "kh" },
  ki: { name: "Kiribati", countryCode: "ki" },
  km: { name: "Comoros", countryCode: "km" },
  kn: { name: "Saint Kitts and Nevis", countryCode: "kn" },
  kp: { name: "North Korea", countryCode: "kp" },
  kr: { name: "South Korea", countryCode: "kr" },
  kw: { name: "Kuwait", countryCode: "kw" },
  ky: { name: "Cayman Islands", countryCode: "ky" },
  kz: { name: "Kazakhstan", countryCode: "kz" },
  la: { name: "Laos", countryCode: "la" },
  lb: { name: "Lebanon", countryCode: "lb" },
  lc: { name: "Saint Lucia", countryCode: "lc" },
  li: { name: "Liechtenstein", countryCode: "li" },
  lk: { name: "Sri Lanka", countryCode: "lk" },
  lr: { name: "Liberia", countryCode: "lr" },
  ls: { name: "Lesotho", countryCode: "ls" },
  lt: { name: "Lithuania", countryCode: "lt" },
  lu: { name: "Luxembourg", countryCode: "lu" },
  lv: { name: "Latvia", countryCode: "lv" },
  ly: { name: "Libya", countryCode: "ly" },
  ma: { name: "Morocco", countryCode: "ma" },
  mc: { name: "Monaco", countryCode: "mc" },
  md: { name: "Moldova", countryCode: "md" },
  me: { name: "Montenegro", countryCode: "me" },
  mf: { name: "Saint Martin", countryCode: "mf" },
  mg: { name: "Madagascar", countryCode: "mg" },
  mk: { name: "North Macedonia", countryCode: "mk" },
  ml: { name: "Mali", countryCode: "ml" },
  mm: { name: "Myanmar", countryCode: "mm" },
  mn: { name: "Mongolia", countryCode: "mn" },
  mo: { name: "Macao", countryCode: "mo" },
  mq: { name: "Martinique", countryCode: "mq" },
  mr: { name: "Mauritania", countryCode: "mr" },
  ms: { name: "Montserrat", countryCode: "ms" },
  mt: { name: "Malta", countryCode: "mt" },
  mu: { name: "Mauritius", countryCode: "mu" },
  mv: { name: "Maldives", countryCode: "mv" },
  mw: { name: "Malawi", countryCode: "mw" },
  mx: { name: "Mexico", countryCode: "mx" },
  my: { name: "Malaysia", countryCode: "my" },
  mz: { name: "Mozambique", countryCode: "mz" },
  na: { name: "Namibia", countryCode: "na" },
  nc: { name: "New Caledonia", countryCode: "nc" },
  ne: { name: "Niger", countryCode: "ne" },
  nf: { name: "Norfolk Island", countryCode: "nf" },
  ng: { name: "Nigeria", countryCode: "ng" },
  ni: { name: "Nicaragua", countryCode: "ni" },
  nl: { name: "Netherlands", countryCode: "nl" },
  no: { name: "Norway", countryCode: "no" },
  np: { name: "Nepal", countryCode: "np" },
  nr: { name: "Nauru", countryCode: "nr" },
  nu: { name: "Niue", countryCode: "nu" },
  nz: { name: "New Zealand", countryCode: "nz" },
  om: { name: "Oman", countryCode: "om" },
  pa: { name: "Panama", countryCode: "pa" },
  pe: { name: "Peru", countryCode: "pe" },
  pf: { name: "French Polynesia", countryCode: "pf" },
  pg: { name: "Papua New Guinea", countryCode: "pg" },
  ph: { name: "Philippines", countryCode: "ph" },
  pk: { name: "Pakistan", countryCode: "pk" },
  pl: { name: "Poland", countryCode: "pl" },
  pm: { name: "Saint Pierre and Miquelon", countryCode: "pm" },
  pn: { name: "Pitcairn Islands", countryCode: "pn" },
  pr: { name: "Puerto Rico", countryCode: "pr" },
  pt: { name: "Portugal", countryCode: "pt" },
  pw: { name: "Palau", countryCode: "pw" },
  py: { name: "Paraguay", countryCode: "py" },
  qa: { name: "Qatar", countryCode: "qa" },
  re: { name: "Réunion", countryCode: "re" },
  ro: { name: "Romania", countryCode: "ro" },
  rs: { name: "Serbia", countryCode: "rs" },
  ru: { name: "Russia", countryCode: "ru" },
  rw: { name: "Rwanda", countryCode: "rw" },
  sa: { name: "Saudi Arabia", countryCode: "sa" },
  sb: { name: "Solomon Islands", countryCode: "sb" },
  sc: { name: "Seychelles", countryCode: "sc" },
  sd: { name: "Sudan", countryCode: "sd" },
  se: { name: "Sweden", countryCode: "se" },
  sg: { name: "Singapore", countryCode: "sg" },
  si: { name: "Slovenia", countryCode: "si" },
  sk: { name: "Slovakia", countryCode: "sk" },
  sl: { name: "Sierra Leone", countryCode: "sl" },
  sm: { name: "San Marino", countryCode: "sm" },
  sn: { name: "Senegal", countryCode: "sn" },
  so: { name: "Somalia", countryCode: "so" },
  sr: { name: "Suriname", countryCode: "sr" },
  ss: { name: "South Sudan", countryCode: "ss" },
  st: { name: "Sao Tome and Principe", countryCode: "st" },
  sv: { name: "El Salvador", countryCode: "sv" },
  sx: { name: "Sint Maarten", countryCode: "sx" },
  sy: { name: "Syria", countryCode: "sy" },
  sz: { name: "Eswatini", countryCode: "sz" },
  td: { name: "Chad", countryCode: "td" },
  tf: { name: "French Southern and Antarctic Lands", countryCode: "tf" },
  tg: { name: "Togo", countryCode: "tg" },
  th: { name: "Thailand", countryCode: "th" },
  tj: { name: "Tajikistan", countryCode: "tj" },
  tk: { name: "Tokelau", countryCode: "tk" },
  tl: { name: "Timor-Leste", countryCode: "tl" },
  tm: { name: "Turkmenistan", countryCode: "tm" },
  tn: { name: "Tunisia", countryCode: "tn" },
  to: { name: "Tonga", countryCode: "to" },
  tr: { name: "Turkey", countryCode: "tr" },
  tt: { name: "Trinidad and Tobago", countryCode: "tt" },
  tw: { name: "Taiwan", countryCode: "tw" },
  tz: { name: "Tanzania", countryCode: "tz" },
  ua: { name: "Ukraine", countryCode: "ua" },
  ug: { name: "Uganda", countryCode: "ug" },
  us: { name: "United States", countryCode: "us" },
  uy: { name: "Uruguay", countryCode: "uy" },
  uz: { name: "Uzbekistan", countryCode: "uz" },
  va: { name: "Vatican City", countryCode: "va" },
  vc: { name: "Saint Vincent and the Grenadines", countryCode: "vc" },
  ve: { name: "Venezuela", countryCode: "ve" },
  vn: { name: "Vietnam", countryCode: "vn" },
  vu: { name: "Vanuatu", countryCode: "vu" },
  ws: { name: "Samoa", countryCode: "ws" },
  ye: { name: "Yemen", countryCode: "ye" },
  yt: { name: "Mayotte", countryCode: "yt" },
  za: { name: "South Africa", countryCode: "za" },
  zm: { name: "Zambia", countryCode: "zm" },
  zw: { name: "Zimbabwe", countryCode: "zw" },
};

export default countries;
